project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Xianlai Yin"
  date: "3/24/2023"
  repo-url: https://github.com/XianlaiYin/XianlaiYin.github.io
  repo-actions: [issue]
  chapters:
    - index.qmd
    - WEEK1.qmd
    - WEEK2.qmd
    - WEEK3.qmd
    - WEEK4.qmd
    - WEEK5.qmd
    - WEEK6.qmd
    - WEEK7.qmd
    - WEEK8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

